source 'https://rubygems.org'

# Specify Ruby version for compatibility
ruby '~> 3.2.5'

# Specify bundler version that works with Ruby 3.3
gem 'bundler', '~> 2.5.16'

gem 'cocoapods'
gem 'cocoapods-pod-linkage'
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'
