name: Build or Update Production

on:
  push:
    branches:
      - main

# Only one can run at a time to not have version race conditions problems
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get Commit Message
        id: commit_msg
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Check for dependency or config changes
        id: check-changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -E "package.json|app.config.ts"; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Run EAS Build
        if: steps.check-changes.outputs.has_changes == 'true'
        run: eas build --platform all --profile production --non-interactive

      - name: Increment version numbers
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          node scripts/build/increment-versions.js
          git add .
          git commit -m "chore: increment version numbers [skip ci]"
          git push https://${{ secrets.PAT_GITHUB }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Run EAS Update
        if: steps.check-changes.outputs.has_changes == 'false'
        run: eas update --auto --profile production --message "${{ steps.commit_msg.outputs.message }}" --non-interactive
