name: Production Deployment

on:
  push:
    branches:
      - production

# We need to ensure only one workflow runs at a time and wait for any in-progress workflows to complete.
# This is critical because:
# 1. If we merge multiple PRs to main (preview env), each triggers a preview deployment that may increment versions
# 2. When we then deploy to production, we must wait for all preview deployments to finish
# 3. Otherwise, we might miss version increments and deploy the wrong build
# Example: PR1 with native changes merged to main -> PR1's preview deploy starts incrementing version ->
# If prod deploy starts before PR1's preview deploy finishes, we'll merge main to production with old version ->
# This causes prod to do EAS update when it should have done EAS build with version increment
concurrency:
  group: "deployment"
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      # Verify that the required Expo token is available
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret"
            exit 1
          fi

      # Get the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB }}

      # Set up Git with bot credentials for commits
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Check if the versions in main and production branches match
      - name: Compare versions with main
        id: version-compare
        run: |
          git fetch origin main
          MAIN_VERSION=$(git show origin/main:package.json | jq -r .version)
          PROD_VERSION=$(jq -r .version package.json)
          if [ "$MAIN_VERSION" != "$PROD_VERSION" ]; then
            echo "versions_match=false" >> $GITHUB_OUTPUT
          else
            echo "versions_match=true" >> $GITHUB_OUTPUT
          fi

      # Collect all commit messages between main and production for the update message
      - name: Get Commit Messages
        id: commit_msg
        run: |
          # Get all commits that are in main but not in production
          COMMITS=$(git log origin/production..origin/main --pretty=format:"- %s")
          # Escape newlines and special characters for GitHub Actions
          COMMITS="${COMMITS//'%'/'%25'}"
          COMMITS="${COMMITS//$'\n'/'%0A'}"
          COMMITS="${COMMITS//$'\r'/'%0D'}"
          echo "message=$COMMITS" >> $GITHUB_OUTPUT

      # Set up Expo Application Services (EAS) CLI
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Create a temporary merge to test deployment safety. If deployment fails,
      # we can cleanly roll back without corrupting production branch history
      - name: Create temporary merge
        id: temp_merge
        run: |
          # Store the current production HEAD for potential rollback
          echo "old_head=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          # Create temporary merge
          git fetch origin main
          git merge origin/main --no-commit --no-ff
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "temp: Temporary merge for deployment verification"

      # Set up Node.js environment
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - run: corepack enable

      # Install project dependencies
      - name: Install dependencies
        run: yarn install

      # Build new app binary if versions don't match
      - name: Build for production
        if: steps.version-compare.outputs.versions_match == 'false'
        run: |
          node scripts/build/ios/production.js
          eas build --platform all --profile production --non-interactive --auto-submit

      # Upload source maps after build
      - name: Upload source maps after build
        if: steps.version-compare.outputs.versions_match == 'false'
        run: npx sentry-expo-upload-sourcemaps dist

      # Deploy OTA update if versions match
      - name: Run EAS Update
        if: steps.version-compare.outputs.versions_match == 'true'
        run: eas update --auto --channel=production --message "${{ steps.commit_msg.outputs.message }}" --non-interactive

      # Upload source maps after update
      - name: Upload source maps after update
        if: steps.version-compare.outputs.versions_match == 'true'
        run: npx sentry-expo-upload-sourcemaps dist

      # If deployment succeeds, merge main into production permanently
      - name: Finalize merge
        if: success()
        run: |
          git fetch origin main
          git merge origin/main -m "feat: Production deployment%0A%0AChanges included:%0A${{ steps.commit_msg.outputs.message }}"
          git push https://${{ secrets.PAT_GITHUB }}@github.com/${{ github.repository }}.git HEAD:production

      # If deployment fails, revert production branch to previous state
      - name: Rollback on failure
        if: failure()
        run: |
          git reset --hard ${{ steps.temp_merge.outputs.old_head }}
          git push --force https://${{ secrets.PAT_GITHUB }}@github.com/${{ github.repository }}.git HEAD:production
